### ISSUE TITLE
Nuget?

### ISSUE THREAD

**Issue by escamoteur** [DevsDNA/XFParallax#1]
Hi, 

this is an absolute amazing control. Thanks a lot for sharing!

What about making a nuget out of it?

All the best
Thomas

**Comment by josueyeray** [comment]
Hi @escamoteur 

thanks for your comment, awesome you like it. We are working on the NuGet package, hope it will be available in the next weeks!

**Comment by escamoteur** [comment]
Actually my current client wanted to have this and I had to tell him, sorry not so easy to do so now we are using a ListView with a Header. As soon as your nuget is out I will switch over

**Comment by josueyeray** [comment]
The NuGet package is available now: https://www.nuget.org/packages/DevsDNA.XFParallax/

Hope it helps you @escamoteur
