### ISSUE TITLE
Breaking app with Xamarin Forms 3.2.0.839982

### ISSUE THREAD

**Issue by LeoJHarris** [DevsDNA/XFParallax#7]
There is an issue with this library using latest XF 3.2.0.839982.

All pages when navigated to with parallax throwing exception:

Unhandled Exception: System.MissingMethodException: void Xamarin.Forms.Internals.INameScope.RegisterName(string,object,System.Xml.IXmlLineInfo) occurred

Having removed your component from my project the issue went away. Also re-adding your component directly and upgrading XF to v3.2.0.839982 the issue also went away.

Upgrade your XF on the lib, would be good as well too migrate to .net standard replacing the existing PCL.

**Comment by arvindbca123** [comment]
There is an issue with this library using latest Xamarin Forms 3.4.0.1009999

when navigate on parallax page 
Unhandled Exception: System.MissingMethodException: void Xamarin.Forms.Internals.INameScope.RegisterName(string,object,System.Xml.IXmlLineInfo) occurred

could you help me please?

**Comment by LeoJHarris** [comment]
@arvindbca123 your best bet is to clone repo and update XF package on lib manually. It seems the author of this package is no longer supporting it from what i gathered.

**Comment by MohanaSundharamMurugan** [comment]
I'm still getting this error! :(
System.MissingMethodException: 'Method not found: void Xamarin.Forms.Internals.INameScope.RegisterName(string,object,System.Xml.IXmlLineInfo)

**Comment by MohanaSundharamMurugan** [comment]
Can you help me with this to resolve?
